# fly.toml app configuration file generated for terrorsquad-go-lenslocked on 2023-10-16T20:51:57+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "terrorsquad-go-lenslocked"
primary_region = "otp"

[build]
dockerfile = "Dockerfile"

[env]
PSQL_PORT = "5432"
PSQL_HOST = "snowy-wind-2243.internal"

[mounts]
source = "lenslocked_storage"
destination = "/app/storage"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
